language: cpp
compiler:
  - clang
  - gcc
install:
  - gem install ronn
  - sudo add-apt-repository -y ppa:wnoronha/thrift
  - sudo add-apt-repository -y ppa:boost-latest/ppa
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
  - sudo apt-get install -qq thrift-compiler libthrift-dev libboost1.55-dev
  - if [ "$CXX" = "g++" ]; then sudo apt-get install -qq g++-4.8; export CXX="g++-4.8"; fi
script: make all
after_success: sudo make install
