language: cpp
compiler:
  - clang
  - gcc
env:
  - BUILDDIR=.
  - BUILDDIR=build

before_install:
  - sudo add-apt-repository -y ppa:wnoronha/thrift
  - sudo add-apt-repository -y ppa:boost-latest/ppa
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo add-apt-repository -y ppa:tuleu/precise-backports
  - sudo apt-get update -qq
install:
  - gem install ronn
  - sudo apt-get install -qq thrift-compiler libthrift-dev libboost1.55-dev libgoogle-glog-dev
  - if [ "$CXX" = "g++" ]; then sudo apt-get install -qq g++-4.8; export CXX="g++-4.8"; fi

before_script:
  - mkdir -p "$BUILDDIR"
  - cd "$BUILDDIR"
script:
  - make -f "$OLDPWD/Makefile" all
  - sudo make -f "$OLDPWD/Makefile" install
